### ISSUE TITLE
Error processing sphum for MJO_prop_amp

### ISSUE THREAD

**Issue by jkrasting** [NOAA-GFDL/MDTF-diagnostics#105]
@tsjackson-noaa --

@wrongkindofdoctor and @jkrasting are both seeing similar error:

```
ERROR: Caught exception processing <#4.MJO_prop_amp:hus (=sphum) @ 1day> with data_key=(44,): DataPreprocessError(Data preprocessing error for data in hus: Preprocessing on <#4.MJO_prop_amp:hus> failed at ConvertUnitsFunction.)
Traceback (most recent call last):
  File "/Users/krasting/mdtf/MDTF-diagnostics/src/preprocessor.py", line 578, in process
    ds = f.process(var, ds)
  File "/Users/krasting/mdtf/MDTF-diagnostics/src/preprocessor.py", line 289, in process
    ds[c.name] = util.convert_dataarray(ds[c.name], dest_c.units)
  File "/Users/krasting/mdtf/MDTF-diagnostics/src/util/units.py", line 136, in convert_dataarray
    da.values = Units.conform(da.values, source_unit, dest_unit, inplace=True)
  File "/Users/krasting/miniconda3/envs/_MDTF_base/lib/python3.7/site-packages/xarray/core/common.py", line 257, in __setattr__
    object.__setattr__(self, name, value)
  File "/Users/krasting/miniconda3/envs/_MDTF_base/lib/python3.7/site-packages/xarray/core/dataarray.py", line 632, in values
    self.variable.values = value
  File "/Users/krasting/miniconda3/envs/_MDTF_base/lib/python3.7/site-packages/xarray/core/variable.py", line 2435, in values
    f"Cannot assign to the .values attribute of dimension coordinate a.k.a IndexVariable {self.name!r}. "
ValueError: Cannot assign to the .values attribute of dimension coordinate a.k.a IndexVariable 'pfull'. Please use DataArray.assign_coords, Dataset.assign_coords or Dataset.assign as appropriate.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/krasting/mdtf/MDTF-diagnostics/src/data_manager.py", line 643, in preprocess_data
    pod.preprocessor.process(v)
  File "/Users/krasting/mdtf/MDTF-diagnostics/src/preprocessor.py", line 581, in process
    f"failed at {f.__class__.__name__}."), var) from exc
```

**Comment by tsjackson-noaa** [comment]
Hi guys, thanks for your patience on this. I've verified that the linked commit fixes this issue: MJO_prop_amp runs successfully on the GFDL.CM4.c96L32.am4g10r8 sample data (as configured in [default_tests.jsonc](https://github.com/NOAA-GFDL/MDTF-diagnostics/blob/feature/v3alpha3/src/default_tests.jsonc)). Will close this issue when we sync up on testing in the Tuesday or Wednesday meetings (want to hear if anyone's able to confirm this; otherwise it's ok if you don't have time to revisit this).

I've pushed the [feature/v3alpha3](https://github.com/NOAA-GFDL/MDTF-diagnostics/tree/feature/v3alpha3) branch to NOAA-GFDL's repo, so that it's no longer necessary to add my repo as a remote for testing.
