### ISSUE TITLE
strftime breaks on dates <1900

### ISSUE THREAD

**Issue by tsjackson-noaa** [NOAA-GFDL/MDTF-diagnostics#12]
Apparently a known issue in py2.7:
https://stackoverflow.com/q/10263956

## Steps to reproduce:
/home/mdteam/DET/analysis/mdtf/MDTF-diagnostics/src/mdtf_gfdl.py --FIRSTYR=1977 --LASTYR=1982 --model='CESM2' --experiment='historical' --OUTPUT_DIR='/nbhome/jp
k/mdtf'

## Output:
[...]

Selected UndecidedKey(table_id='Amon', grid_label='gn', version_date='20190308') for zg @ mon
Traceback (most recent call last):
  File "/home/mdteam/DET/analysis/mdtf/MDTF-diagnostics/src/mdtf_gfdl.py", line 92, in <module>
    main()
  File "/home/mdteam/DET/analysis/mdtf/MDTF-diagnostics/src/mdtf_gfdl.py", line 88, in main
    mdtf.main_case_loop(config, DataMgr, EnvironmentMgr)
  File "/home/mdteam/DET/analysis/mdtf/MDTF-diagnostics/src/mdtf.py", line 232, in main_case_loop
    case.fetch_data()
  File "/home/mdteam/DET/analysis/mdtf/MDTF-diagnostics/src/data_manager.py", line 347, in fetch_data
    self.plan_data_fetch_hook()
  File "/home/mdteam/DET/analysis/mdtf/MDTF-diagnostics/src/gfdl.py", line 346, in plan_data_fetch_hook
    self.data_files[data_key] = self._component_map[u_key, data_key]
  File "/home/mdteam/DET/analysis/mdtf/MDTF-diagnostics/src/util.py", line 145, in __setitem__
    super(MultiMap, self).__setitem__(key, coerce_to_collection(value, set))
  File "/home/mdteam/DET/analysis/mdtf/MDTF-diagnostics/src/util.py", line 641, in coerce_to_collection
    return coll_type(obj)
  File "/home/mdteam/DET/analysis/mdtf/MDTF-diagnostics/src/util.py", line 349, in __hash__
    return hash(self._freeze())
  File "/home/mdteam/DET/analysis/mdtf/MDTF-diagnostics/src/data_manager.py", line 116, in _freeze
    d2 = {k: repr(d[k]) for k in keys_to_hash}
  File "/home/mdteam/DET/analysis/mdtf/MDTF-diagnostics/src/data_manager.py", line 116, in <dictcomp>
    d2 = {k: repr(d[k]) for k in keys_to_hash}
  File "/home/mdteam/DET/analysis/mdtf/MDTF-diagnostics/src/datelabel.py", line 232, in __repr__
    return "DateRange('{}')".format(self)
  File "/home/mdteam/DET/analysis/mdtf/MDTF-diagnostics/src/datelabel.py", line 228, in format
    return '{}-{}'.format(self.start, self.end)
  File "/home/mdteam/DET/analysis/mdtf/MDTF-diagnostics/src/datelabel.py", line 62, in format
    return self.strftime(self._strftimes[self.precision])
ValueError: year=1850 is before 1900; the datetime strftime() methods require year >= 1900

**Comment by tsjackson-noaa** [comment]
Verified above commit fixes the issue.
