### ISSUE TITLE
'function' object has no attribute 'endswith' for _cmip6_root

### ISSUE THREAD

**Issue by tsjackson-noaa** [NOAA-GFDL/MDTF-diagnostics#13]
Hi Tom -

Thanks for the updates.  I just tried the CESM2 case and hit an error:

/home/mdteam/DET/analysis/mdtf/MDTF-diagnostics/src/mdtf_gfdl.py --FIRSTYR=1977 --LASTYR=1982 --model='CESM2' --experiment='historical' --OUTPUT_DIR='/nbhome/jpk/mdtf'

Traceback (most recent call last):
  File "/home/mdteam/DET/analysis/mdtf/MDTF-diagnostics/src/mdtf_gfdl.py", line 117, in <module>
    mdtf.main_loop()
  File "/home/mdteam/DET/analysis/mdtf/MDTF-diagnostics/src/mdtf.py", line 271, in main_loop
    case = self.DataManager(case_dict, self.config)
  File "/home/mdteam/DET/analysis/mdtf/MDTF-diagnostics/src/gfdl.py", line 220, in GfdlautoDataManager
    return Gfdludacmip6DataManager(case_dict, config, DateFreqMixin)
  File "/home/mdteam/DET/analysis/mdtf/MDTF-diagnostics/src/gfdl.py", line 664, in __init__
    self.source_id, self.experiment_id, self.member_id)
  File "/usr/local/python/2.7.12/lib/python2.7/posixpath.py", line 70, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'function' object has no attribute 'endswith'

-John

**Comment by tsjackson-noaa** [comment]
Verifed above commit fixes the issue.
