### ISSUE TITLE
did we lose the ability to use "" to set OUTPUT_DIR = WORKING_DIR?

### ISSUE THREAD

**Issue by bitterbark** [NOAA-GFDL/MDTF-diagnostics#88]
https://github.com/NOAA-GFDL/MDTF-diagnostics/blob/f0661e612006d8b14b646f2fdb6fe900e690987f/src/default_tests.jsonc#L77

In default_test.jsonc, it used to be that setting
 "OUTPUT_DIR": ""
would set OUTPUT_DIR = WORKING_DIR.

With latest version from develop, this now results in a python error ( included below).
Is there an updated way to do this?

Making the user change something in two places will lead to errors.

BTW, the file name default_tests implies it is part of the test suite. If the file was named input_defaults, it would be easier to understand its function. It is also weird to me it is in src directory instead of with the executable. 

- _unittest: false
  CODE_ROOT: /home/bundy/mdtf/MDTF-diagnostics-clone.20201115
Traceback (most recent call last):
  File "/project/amp/bundy/anaconda2/envs/_MDTF_base/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/project/amp/bundy/anaconda2/envs/_MDTF_base/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/bundy/mdtf/MDTF-diagnostics-clone.20201115/src/mdtf.py", line 319, in <module>
    mdtf = MDTFFramework(code_root, defaults_rel_path)
  File "/home/bundy/mdtf/MDTF-diagnostics-clone.20201115/src/mdtf.py", line 60, in __init__
    self._framework_init(code_root, defaults_rel_path)
  File "/home/bundy/mdtf/MDTF-diagnostics-clone.20201115/src/mdtf.py", line 82, in _framework_init
    self.parse_mdtf_args(cli_obj, config)
  File "/home/bundy/mdtf/MDTF-diagnostics-clone.20201115/src/mdtf.py", line 114, in parse_mdtf_args
    self.parse_paths(cli_obj, config)
  File "/home/bundy/mdtf/MDTF-diagnostics-clone.20201115/src/mdtf.py", line 207, in parse_paths
    config.paths.parse(cli_obj.config, cli_obj.custom_types.get('path', []))
  File "/home/bundy/mdtf/MDTF-diagnostics-clone.20201115/src/util_mdtf.py", line 43, in parse
    self[key] = self._init_path(key, d, env=env)
  File "/home/bundy/mdtf/MDTF-diagnostics-clone.20201115/src/util_mdtf.py", line 63, in _init_path
    util.coerce_from_iter(d[key]), root_path=self.CODE_ROOT, env=env
  File "/home/bundy/mdtf/MDTF-diagnostics-clone.20201115/src/util.py", line 427, in resolve_path
    path = os.path.expanduser(path) # resolve '~' to home dir
  File "/project/amp/bundy/anaconda2/envs/_MDTF_base/lib/python3.7/posixpath.py", line 235, in expanduser
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by wrongkindofdoctor** [comment]
I'm not sure about the reasoning for changing the default action for empty strings, but users need to provide something (or leave the default path). Perhaps we can add comments to the default jsonc files stating that strings cannot be empty for non-optional arguments.

**Comment by bitterbark** [comment]
Definitely having a comment would be good since it is changed functionality. But since I’ve always had outdir = wrkdir, my guess is that others do too, and I don’t think it is good practice to require users to make two identical changes. How about if outdir was an optional setting, with its default being wrkdir?

**Comment by jkrasting** [comment]
Makes sense to me @bitterbark.  Looks like we are setting `WORKING_DIR` to `OUTPUT_DIR` if missing, but not the opposite.

https://github.com/NOAA-GFDL/MDTF-diagnostics/blob/b1488afc126d2f81df4488634a7de8cf11a8f910/src/util_mdtf.py#L47-L54

**Comment by tsjackson-noaa** [comment]
Closing this issue, as it's fixed by PR #157.
